version: '3.7'

services:
  nginx:
    image: nginx:latest

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/core:/etc/nginx/conf.d
      - ./src:/var/www/
      - ./docker/log/nginx:/var/log/nginx/
      - ./docker/nginx/html:/usr/share/nginx/html/
    links:
      - php

  mysql:
    image: percona:latest
    ports:
      - "3309:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=oxana"
      - "MYSQL_USER=oxana"
      - "MYSQL_PASSWORD=123456"
    volumes:
      - "./docker/mysql:/var/lib/mysql:delegated"

  php:
    build: docker/php
    volumes:
      - ./src:/var/www
      - ./xhprof:/var/www/xhprof:delegated
      - ./docker/log/php:/var/log/php/
      - ./docker/profile:/root:delegated
      - ./docker/php/xdebug/profile:/tmp/xdebug/profile/
    links:
      - mysql